document.getElementById("items").innerHTML = `<tr><td>1</td><td>تحديد الأهداف بوضوح</td><td><input class="rate" type="radio" name="r1" value="excellent"></td><td><input class="rate" type="radio" name="r1" value="good"></td><td><input class="rate" type="radio" name="r1" value="acceptable"></td></tr>
<tr><td>2</td><td>استخدام استراتيجيات متنوعة</td><td><input class="rate" type="radio" name="r2" value="excellent"></td><td><input class="rate" type="radio" name="r2" value="good"></td><td><input class="rate" type="radio" name="r2" value="acceptable"></td></tr>
<tr><td>3</td><td>توظيف الوسائل التعليمية</td><td><input class="rate" type="radio" name="r3" value="excellent"></td><td><input class="rate" type="radio" name="r3" value="good"></td><td><input class="rate" type="radio" name="r3" value="acceptable"></td></tr>
<tr><td>4</td><td>مراعاة الفروق الفردية</td><td><input class="rate" type="radio" name="r4" value="excellent"></td><td><input class="rate" type="radio" name="r4" value="good"></td><td><input class="rate" type="radio" name="r4" value="acceptable"></td></tr>
<tr><td>5</td><td>تنويع أنماط التعلم</td><td><input class="rate" type="radio" name="r5" value="excellent"></td><td><input class="rate" type="radio" name="r5" value="good"></td><td><input class="rate" type="radio" name="r5" value="acceptable"></td></tr>
<tr><td>6</td><td>إثارة دافعية الطلاب</td><td><input class="rate" type="radio" name="r6" value="excellent"></td><td><input class="rate" type="radio" name="r6" value="good"></td><td><input class="rate" type="radio" name="r6" value="acceptable"></td></tr>
<tr><td>7</td><td>وضوح الشرح والتسلسل</td><td><input class="rate" type="radio" name="r7" value="excellent"></td><td><input class="rate" type="radio" name="r7" value="good"></td><td><input class="rate" type="radio" name="r7" value="acceptable"></td></tr>
<tr><td>8</td><td>استخدام الأسئلة الصفية</td><td><input class="rate" type="radio" name="r8" value="excellent"></td><td><input class="rate" type="radio" name="r8" value="good"></td><td><input class="rate" type="radio" name="r8" value="acceptable"></td></tr>
<tr><td>9</td><td>تنمية مهارات التفكير</td><td><input class="rate" type="radio" name="r9" value="excellent"></td><td><input class="rate" type="radio" name="r9" value="good"></td><td><input class="rate" type="radio" name="r9" value="acceptable"></td></tr>
<tr><td>10</td><td>إدارة وقت الحصة</td><td><input class="rate" type="radio" name="r10" value="excellent"></td><td><input class="rate" type="radio" name="r10" value="good"></td><td><input class="rate" type="radio" name="r10" value="acceptable"></td></tr>
<tr><td>11</td><td>تعزيز مشاركة الطلاب</td><td><input class="rate" type="radio" name="r11" value="excellent"></td><td><input class="rate" type="radio" name="r11" value="good"></td><td><input class="rate" type="radio" name="r11" value="acceptable"></td></tr>
<tr><td>12</td><td>التقويم البنائي المستمر</td><td><input class="rate" type="radio" name="r12" value="excellent"></td><td><input class="rate" type="radio" name="r12" value="good"></td><td><input class="rate" type="radio" name="r12" value="acceptable"></td></tr>
<tr><td>13</td><td>تشجيع طرح الأسئلة</td><td><input class="rate" type="radio" name="r13" value="excellent"></td><td><input class="rate" type="radio" name="r13" value="good"></td><td><input class="rate" type="radio" name="r13" value="acceptable"></td></tr>
<tr><td>14</td><td>توظيف التقنية في التعليم</td><td><input class="rate" type="radio" name="r14" value="excellent"></td><td><input class="rate" type="radio" name="r14" value="good"></td><td><input class="rate" type="radio" name="r14" value="acceptable"></td></tr>
<tr><td>15</td><td>تحفيز العمل الجماعي</td><td><input class="rate" type="radio" name="r15" value="excellent"></td><td><input class="rate" type="radio" name="r15" value="good"></td><td><input class="rate" type="radio" name="r15" value="acceptable"></td></tr>
<tr><td>16</td><td>تنمية القيم والاتجاهات</td><td><input class="rate" type="radio" name="r16" value="excellent"></td><td><input class="rate" type="radio" name="r16" value="good"></td><td><input class="rate" type="radio" name="r16" value="acceptable"></td></tr>
<tr><td>17</td><td>القدرة على ضبط الصف</td><td><input class="rate" type="radio" name="r17" value="excellent"></td><td><input class="rate" type="radio" name="r17" value="good"></td><td><input class="rate" type="radio" name="r17" value="acceptable"></td></tr>
<tr><td>18</td><td>استخدام لغة عربية سليمة</td><td><input class="rate" type="radio" name="r18" value="excellent"></td><td><input class="rate" type="radio" name="r18" value="good"></td><td><input class="rate" type="radio" name="r18" value="acceptable"></td></tr>
<tr><td>19</td><td>تنويع مصادر التعلم</td><td><input class="rate" type="radio" name="r19" value="excellent"></td><td><input class="rate" type="radio" name="r19" value="good"></td><td><input class="rate" type="radio" name="r19" value="acceptable"></td></tr>
<tr><td>20</td><td>وضوح السبورة والتنظيم</td><td><input class="rate" type="radio" name="r20" value="excellent"></td><td><input class="rate" type="radio" name="r20" value="good"></td><td><input class="rate" type="radio" name="r20" value="acceptable"></td></tr>
<tr><td>21</td><td>إعطاء واجبات مناسبة</td><td><input class="rate" type="radio" name="r21" value="excellent"></td><td><input class="rate" type="radio" name="r21" value="good"></td><td><input class="rate" type="radio" name="r21" value="acceptable"></td></tr>
<tr><td>22</td><td>توضيح عناصر الدرس</td><td><input class="rate" type="radio" name="r22" value="excellent"></td><td><input class="rate" type="radio" name="r22" value="good"></td><td><input class="rate" type="radio" name="r22" value="acceptable"></td></tr>
<tr><td>23</td><td>إبراز النقاط الأساسية</td><td><input class="rate" type="radio" name="r23" value="excellent"></td><td><input class="rate" type="radio" name="r23" value="good"></td><td><input class="rate" type="radio" name="r23" value="acceptable"></td></tr>
<tr><td>24</td><td>تنويع طرق التقويم</td><td><input class="rate" type="radio" name="r24" value="excellent"></td><td><input class="rate" type="radio" name="r24" value="good"></td><td><input class="rate" type="radio" name="r24" value="acceptable"></td></tr>
<tr><td>25</td><td>إعطاء أنشطة إثرائية</td><td><input class="rate" type="radio" name="r25" value="excellent"></td><td><input class="rate" type="radio" name="r25" value="good"></td><td><input class="rate" type="radio" name="r25" value="acceptable"></td></tr>
<tr><td>26</td><td>استخدام أساليب متنوعة</td><td><input class="rate" type="radio" name="r26" value="excellent"></td><td><input class="rate" type="radio" name="r26" value="good"></td><td><input class="rate" type="radio" name="r26" value="acceptable"></td></tr>
<tr><td>27</td><td>التشجيع على النقد</td><td><input class="rate" type="radio" name="r27" value="excellent"></td><td><input class="rate" type="radio" name="r27" value="good"></td><td><input class="rate" type="radio" name="r27" value="acceptable"></td></tr>
<tr><td>28</td><td>توظيف الأنشطة بفاعلية</td><td><input class="rate" type="radio" name="r28" value="excellent"></td><td><input class="rate" type="radio" name="r28" value="good"></td><td><input class="rate" type="radio" name="r28" value="acceptable"></td></tr>`;

function clearForm(){
  if(!confirm("هل تريد مسح جميع البيانات؟")) return;
  document.querySelectorAll("input, textarea").forEach(el=>{
    if(el.type==="radio") el.checked=false;
    else el.value="";
  });
}
